from fpdf import FPDF
import io
from datetime import datetime

class PashuDoctorReport(FPDF):
    def header(self):
        # Logo placeholder or Text
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(46, 125, 50) # Emerald Green
        self.cell(0, 10, 'PashuDoctor \u2014 AI Livestock Health Report', 0, 1, 'C')
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(100)
        self.cell(0, 5, 'Empowering Indian Farmers with AI Diagnostics', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by PashuDoctor AI | {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def generate_pdf_report(case_data: dict) -> bytes:
    """Generates a professional PDF report from case data"""
    pdf = PashuDoctorReport()
    pdf.add_page()
    
    # 1. Case Info Section
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(0)
    pdf.cell(0, 10, 'Case Details', 'B', 1, 'L')
    pdf.ln(2)
    
    pdf.set_font('helvetica', '', 10)
    pdf.cell(40, 7, 'Case ID:', 0, 0)
    pdf.cell(0, 7, f"{case_data.get('case_id', 'N/A')}", 0, 1)
    
    pdf.cell(40, 7, 'Animal Type:', 0, 0)
    pdf.cell(0, 7, f"{case_data.get('animal_type', 'Unknown').capitalize()}", 0, 1)
    
    pdf.cell(40, 7, 'Date:', 0, 0)
    date_str = case_data.get('created_at', datetime.now().isoformat())[:10]
    pdf.cell(0, 7, f"{date_str}", 0, 1)
    pdf.ln(5)

    # 2. Symptoms Section
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Reported Symptoms', 'B', 1, 'L')
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    pdf.multi_cell(0, 7, f"{case_data.get('symptoms_text', 'No description provided.')}")
    pdf.ln(5)

    # 3. Diagnosis Section
    diag = case_data.get('diagnosis', {})
    pdf.set_fill_color(232, 245, 233) # Soft Green
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(46, 125, 50)
    pdf.cell(0, 15, f"Primary Diagnosis: {diag.get('primary_diagnosis', 'Under Evaluation')}", 0, 1, 'L', fill=True)
    pdf.ln(2)
    
    pdf.set_text_color(0)
    pdf.set_font('helvetica', 'B', 10)
    conf = int(case_data.get('confidence_score', 0) * 100)
    pdf.cell(0, 7, f"AI Confidence Score: {conf}%", 0, 1)
    pdf.ln(5)

    # 4. Details Section
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 10, 'Vet Advice & Farmer Instructions', 'B', 1, 'L')
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    pdf.multi_cell(0, 7, f"{diag.get('farmer_advice', 'Follow general animal husbandry practices.')}")
    pdf.ln(5)

    # 5. Precautions
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(183, 28, 28) # Dark Red
    pdf.cell(0, 10, 'Immediate Precautions', 'B', 1, 'L')
    pdf.ln(2)
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(0)
    for p in diag.get('immediate_precautions', []):
        pdf.multi_cell(0, 7, f"- {p}")
    pdf.ln(5)

    # 6. Urgent Referral
    pdf.set_fill_color(255, 243, 224) # Light Orange
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(230, 81, 0) # Dark Orange
    pdf.cell(0, 10, f"Urgency Level: {diag.get('vet_urgency', 'Monitor').upper()}", 0, 1, 'L', fill=True)
    pdf.ln(2)
    
    pdf.set_text_color(0)
    pdf.set_font('helvetica', 'I', 9)
    warning_text = "This AI-generated report is for informational purposes only. It is NOT a substitute for professional veterinary advice. Please present this report to a licensed veterinarian."
    pdf.multi_cell(0, 6, warning_text)

    # Output as bytes
    return pdf.output()
